export interface Project {
  id: string;
  clientId: string;
  title: string;
  description: string;
  type: "VIRTUAL" | "PHYSICAL";
  budgetModel: "FIXED" | "MILESTONE";
  budget: number;
  category: string;
  status: "POSTED" | "ASSIGNED" | "IN_PROGRESS" | "SUBMITTED" | "COMPLETED" | "IN_DISPUTE" | "CANCELLED";
  workerId?: string;
  address?: string;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export const projects: Project[] = [
  // 10 POSTED Projects
  {
    id: "proj-001",
    clientId: "client-001",
    title: "Website Redesign Project",
    description: "Complete redesign of company website with modern UI/UX. Need responsive design compatible with all devices.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 5000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-002",
    clientId: "client-001",
    title: "House Deep Cleaning",
    description: "Professional deep cleaning service for 3 bedroom house including kitchen and bathrooms.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Cleaning",
    status: "POSTED",
    address: "123 Main Street, New York, NY",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-003",
    clientId: "client-001",
    title: "Mobile App for Food Delivery",
    description: "iOS and Android app for food delivery service with real-time tracking and payment integration.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 15000.00,
    category: "Mobile Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-004",
    clientId: "client-001",
    title: "Office Moving Service",
    description: "Need help moving office furniture and equipment to new location within the city.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Moving",
    status: "POSTED",
    address: "456 Business Ave, Chicago, IL",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-005",
    clientId: "client-001",
    title: "Logo Design for Startup",
    description: "Modern, minimalist logo design for tech startup. Need multiple concepts and revisions.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 500.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-006",
    clientId: "client-001",
    title: "Garden Landscaping",
    description: "Complete garden makeover with new plants, pathways, and irrigation system installation.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 4500.00,
    category: "Gardening",
    status: "POSTED",
    address: "789 Oak Lane, Los Angeles, CA",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-007",
    clientId: "client-001",
    title: "SEO Content Writing",
    description: "Write 20 SEO-optimized blog posts for real estate website. Each post 1000-1500 words.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2000.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-008",
    clientId: "client-001",
    title: "Event Photography",
    description: "Professional photography coverage for corporate event. 4 hours coverage with edited photos.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Photography",
    status: "POSTED",
    address: "500 Convention Center, Miami, FL",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-009",
    clientId: "client-001",
    title: "E-commerce Platform Development",
    description: "Build a full-stack e-commerce platform with inventory management and payment processing.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 25000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "proj-010",
    clientId: "client-001",
    title: "Furniture Assembly",
    description: "Assemble 5 pieces of IKEA furniture including wardrobes and bookcases.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 250.00,
    category: "Assembly",
    status: "POSTED",
    address: "321 Pine Street, Seattle, WA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },

  // 10 ONGOING (IN_PROGRESS) Projects
  {
    id: "proj-011",
    clientId: "client-001",
    title: "Weekly Office Cleaning",
    description: "Regular weekly office cleaning for 3 floors including vacuuming, dusting, and bathroom sanitization.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Cleaning",
    status: "IN_PROGRESS",
    workerId: "worker-001",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-012",
    clientId: "client-001",
    title: "API Integration Project",
    description: "Integrate third-party payment APIs and CRM systems into existing web application.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 3500.00,
    category: "Web Development",
    status: "IN_PROGRESS",
    workerId: "worker-002",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-013",
    clientId: "client-001",
    title: "Pet Sitting Service",
    description: "Daily pet sitting for 2 dogs and 1 cat for one week while owner is on vacation.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 450.00,
    category: "Pet Care",
    status: "IN_PROGRESS",
    workerId: "worker-003",
    address: "654 Dogwood Drive, Boston, MA",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-014",
    clientId: "client-001",
    title: "Video Editing for YouTube",
    description: "Edit and produce weekly YouTube videos including thumbnails, intros, and captions.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 2000.00,
    category: "Video Editing",
    status: "IN_PROGRESS",
    workerId: "worker-004",
    createdAt: new Date(Date.now() - 86400000 * 21).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-015",
    clientId: "client-001",
    title: "Carpet Cleaning",
    description: "Deep carpet cleaning for 4 rooms and stairs using professional equipment.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 300.00,
    category: "Cleaning",
    status: "IN_PROGRESS",
    workerId: "worker-005",
    address: "987 Elm Street, Denver, CO",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-016",
    clientId: "client-001",
    title: "Social Media Marketing",
    description: "Manage social media accounts with daily posts, stories, and engagement for 1 month.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1500.00,
    category: "Marketing",
    status: "IN_PROGRESS",
    workerId: "worker-006",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-017",
    clientId: "client-001",
    title: "Handyman Services",
    description: "Various minor repairs including door handle replacement, shelf mounting, and drywall patching.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 400.00,
    category: "Handyman",
    status: "IN_PROGRESS",
    workerId: "worker-007",
    address: "147 Maple Avenue, Portland, OR",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-018",
    clientId: "client-001",
    title: "Custom Software Development",
    description: "Develop inventory management system with barcode scanning and reporting features.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 12000.00,
    category: "Software Development",
    status: "IN_PROGRESS",
    workerId: "worker-008",
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-019",
    clientId: "client-001",
    title: "Personal Training Sessions",
    description: "10 personal training sessions for fitness goals including strength training and cardio.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 750.00,
    category: "Fitness",
    status: "IN_PROGRESS",
    workerId: "worker-009",
    address: "Gold's Gym Downtown, Houston, TX",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-020",
    clientId: "client-001",
    title: "Graphic Design for Marketing",
    description: "Create marketing materials including brochures, flyers, and social media graphics.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 1800.00,
    category: "Design",
    status: "IN_PROGRESS",
    workerId: "worker-010",
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },

  // 10 COMPLETED Projects
  {
    id: "proj-021",
    clientId: "client-001",
    title: "Wedding Photography",
    description: "Full day wedding photography coverage with edited digital album and prints.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 3500.00,
    category: "Photography",
    status: "COMPLETED",
    workerId: "worker-011",
    completedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "proj-022",
    clientId: "client-001",
    title: "Website Development",
    description: "Built professional portfolio website with contact forms and blog integration.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 2800.00,
    category: "Web Development",
    status: "COMPLETED",
    workerId: "worker-012",
    completedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: "proj-023",
    clientId: "client-001",
    title: "Lawn Mowing Service",
    description: "Regular lawn mowing and edging for residential property every 2 weeks.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 200.00,
    category: "Gardening",
    status: "COMPLETED",
    workerId: "worker-013",
    completedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 100).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    id: "proj-024",
    clientId: "client-001",
    title: "Data Analysis Report",
    description: "Analyze sales data and create comprehensive report with visualizations and insights.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Data Analysis",
    status: "COMPLETED",
    workerId: "worker-014",
    completedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "proj-025",
    clientId: "client-001",
    title: "Home Renovation Planning",
    description: "Kitchen and bathroom renovation planning with design drawings and material suggestions.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 5500.00,
    category: "Renovation",
    status: "COMPLETED",
    workerId: "worker-015",
    completedAt: new Date(Date.now() - 86400000 * 75).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 150).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 75).toISOString(),
  },
  {
    id: "proj-026",
    clientId: "client-001",
    title: "Translation Services",
    description: "Translate 50 pages of legal documents from Spanish to English with certification.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1250.00,
    category: "Translation",
    status: "COMPLETED",
    workerId: "worker-016",
    completedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "proj-027",
    clientId: "client-001",
    title: "Dog Walking",
    description: "Daily dog walking service for 2 large dogs, 30 minutes each walk, for 2 weeks.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Pet Care",
    status: "COMPLETED",
    workerId: "worker-017",
    completedAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 55).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 25).toISOString(),
  },
  {
    id: "proj-028",
    clientId: "client-001",
    title: "Mobile App UI Design",
    description: "Design UI/UX for fitness tracking mobile application with screens and prototypes.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 4500.00,
    category: "Design",
    status: "COMPLETED",
    workerId: "worker-018",
    completedAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 110).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 50).toISOString(),
  },
  {
    id: "proj-029",
    clientId: "client-001",
    title: "Furniture Delivery",
    description: "Deliver and assemble new bedroom furniture set from store to apartment.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 275.00,
    category: "Delivery",
    status: "COMPLETED",
    workerId: "worker-019",
    completedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "proj-030",
    clientId: "client-001",
    title: "Accounting Services",
    description: "Monthly bookkeeping and tax preparation for small business.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 800.00,
    category: "Accounting",
    status: "COMPLETED",
    workerId: "worker-020",
    completedAt: new Date(Date.now() - 86400000 * 35).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 80).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
];

export function getProjectsByStatus(status: string): Project[] {
  return projects.filter(p => p.status === status);
}

export function getProjectById(id: string): Project | undefined {
  return projects.find(p => p.id === id);
}

export function getProjectsByClientId(clientId: string): Project[] {
  return projects.filter(p => p.clientId === clientId);
}

export function addProject(project: Omit<Project, "id" | "createdAt" | "updatedAt">): Project {
  const newProject: Project = {
    ...project,
    id: `proj-${Date.now()}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  projects.push(newProject);
  return newProject;
}

export function updateProject(id: string, updates: Partial<Project>): Project | undefined {
  const index = projects.findIndex(p => p.id === id);
  if (index === -1) return undefined;
  
  projects[index] = {
    ...projects[index],
    ...updates,
    updatedAt: new Date().toISOString(),
  };
  return projects[index];
}
