export interface Project {
  id: string;
  clientId: string;
  contractorId?: string;
  title: string;
  description: string;
  type: "VIRTUAL" | "PHYSICAL";
  budgetModel: "FIXED" | "MILESTONE";
  budget: number;
  category: string;
  status: "POSTED" | "ASSIGNED" | "IN_PROGRESS" | "SUBMITTED" | "COMPLETED" | "IN_DISPUTE" | "CANCELLED";
  workerId?: string;
  address?: string;
  completedAt?: string;
  createdAt: string;
  updatedAt: string;
  contractorOnly?: boolean;
}

export const projects: Project[] = [
  // 10 POSTED Projects
  {
    id: "proj-001",
    clientId: "client-001",
    contractorId: "contractor-001",
    title: "Website Redesign Project",
    description: "Complete redesign of company website with modern UI/UX. Need responsive design compatible with all devices.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 5000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-002",
    clientId: "client-001",
    title: "House Deep Cleaning",
    description: "Professional deep cleaning service for 3 bedroom house including kitchen and bathrooms.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Cleaning",
    status: "POSTED",
    address: "123 Main Street, New York, NY",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-003",
    clientId: "client-001",
    contractorId: "contractor-001",
    title: "Mobile App for Food Delivery",
    description: "iOS and Android app for food delivery service with real-time tracking and payment integration.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 15000.00,
    category: "Mobile Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-004",
    clientId: "client-001",
    title: "Office Moving Service",
    description: "Need help moving office furniture and equipment to new location within the city.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Moving",
    status: "POSTED",
    address: "456 Business Ave, Chicago, IL",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-005",
    clientId: "client-001",
    contractorId: "contractor-001",
    title: "Logo Design for Startup",
    description: "Modern, minimalist logo design for tech startup. Need multiple concepts and revisions.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 500.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-006",
    clientId: "client-001",
    title: "Garden Landscaping",
    description: "Complete garden makeover with new plants, pathways, and irrigation system installation.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 4500.00,
    category: "Gardening",
    status: "POSTED",
    address: "789 Oak Lane, Los Angeles, CA",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-007",
    clientId: "client-001",
    title: "SEO Content Writing",
    description: "Write 20 SEO-optimized blog posts for real estate website. Each post 1000-1500 words.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2000.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-008",
    clientId: "client-001",
    title: "Event Photography",
    description: "Professional photography coverage for corporate event. 4 hours coverage with edited photos.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Photography",
    status: "POSTED",
    address: "500 Convention Center, Miami, FL",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-009",
    clientId: "client-001",
    title: "E-commerce Platform Development",
    description: "Build a full-stack e-commerce platform with inventory management and payment processing.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 25000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "proj-010",
    clientId: "client-001",
    title: "Furniture Assembly",
    description: "Assemble 5 pieces of IKEA furniture including wardrobes and bookcases.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 250.00,
    category: "Assembly",
    status: "POSTED",
    address: "321 Pine Street, Seattle, WA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },

  // Additional 90 POSTED Projects for worker browse (proj-101 to proj-190)
  {
    id: "proj-101",
    clientId: "client-001",
    title: "WordPress Blog Setup",
    description: "Set up a professional WordPress blog with SEO plugins, theme customization, and content structure.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 450.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-102",
    clientId: "client-001",
    title: "House Painting Interior",
    description: "Interior painting for 3 bedroom house including walls, ceilings, and trim. Paint provided.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2500.00,
    category: "Painting",
    status: "POSTED",
    address: "890 Maple Drive, Austin, TX",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-103",
    clientId: "client-001",
    title: "Python Data Scraping",
    description: "Build a web scraper to collect product prices from e-commerce sites and export to CSV.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 1200.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-104",
    clientId: "client-001",
    title: "Pool Maintenance Weekly",
    description: "Weekly pool cleaning and chemical balancing for residential swimming pool.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 150.00,
    category: "Cleaning",
    status: "POSTED",
    address: "234 Palm Ave, Phoenix, AZ",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-105",
    clientId: "client-001",
    title: "React Native App Development",
    description: "Build a cross-platform mobile app for task management with offline sync capabilities.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 18000.00,
    category: "Mobile Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-106",
    clientId: "client-001",
    title: "Snow Removal Service",
    description: "Snow removal for driveway and walkways during winter season. 10 visits included.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 500.00,
    category: "Cleaning",
    status: "POSTED",
    address: "567 Winter Lane, Minneapolis, MN",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-107",
    clientId: "client-001",
    title: "Brand Identity Design",
    description: "Complete brand identity package including logo, color palette, typography, and brand guidelines.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 3000.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-108",
    clientId: "client-001",
    title: "Electrical Repair Work",
    description: "Fix faulty outlets, replace light fixtures, and upgrade electrical panel for home.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 950.00,
    category: "Handyman",
    status: "POSTED",
    address: "789 Circuit Road, San Diego, CA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-109",
    clientId: "client-001",
    title: "Technical Documentation",
    description: "Write comprehensive API documentation for REST endpoints with examples and guides.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1800.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-110",
    clientId: "client-001",
    title: "Driveway Power Washing",
    description: "Power wash driveway, patio, and walkways to remove stains and buildup.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Cleaning",
    status: "POSTED",
    address: "321 Clean Street, Tampa, FL",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-111",
    clientId: "client-001",
    title: "Vue.js Dashboard Development",
    description: "Build an admin dashboard with Vue.js including charts, tables, and user management.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 8500.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-112",
    clientId: "client-001",
    title: "Tree Trimming Service",
    description: "Trim and shape trees in backyard, remove dead branches, and haul away debris.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Gardening",
    status: "POSTED",
    address: "456 Forest View, Charlotte, NC",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-113",
    clientId: "client-001",
    title: "Email Marketing Campaign",
    description: "Design and set up email marketing campaign with automation flows and analytics tracking.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1100.00,
    category: "Marketing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-114",
    clientId: "client-001",
    title: "Plumbing Repair",
    description: "Fix leaky faucets, unclog drains, and replace old pipes in bathroom and kitchen.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 700.00,
    category: "Handyman",
    status: "POSTED",
    address: "678 Water Way, Nashville, TN",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-115",
    clientId: "client-001",
    title: "Machine Learning Model",
    description: "Develop a recommendation system using Python and TensorFlow for product suggestions.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 12000.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-116",
    clientId: "client-001",
    title: "Cat Grooming Service",
    description: "Full grooming service for 2 cats including bath, nail trim, and hair styling.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 120.00,
    category: "Pet Care",
    status: "POSTED",
    address: "890 Kitty Lane, Portland, OR",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-117",
    clientId: "client-001",
    title: "YouTube Video Editing",
    description: "Edit 10 YouTube videos with intro, outro, transitions, and color grading.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1500.00,
    category: "Video Editing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-118",
    clientId: "client-001",
    title: "Fence Installation",
    description: "Install 200 linear feet of wooden privacy fence with gate and post caps.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 3500.00,
    category: "Assembly",
    status: "POSTED",
    address: "234 Backyard Blvd, Indianapolis, IN",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-119",
    clientId: "client-001",
    title: "Product Photography",
    description: "Professional product photography for 50 items with white background and lifestyle shots.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2000.00,
    category: "Photography",
    status: "POSTED",
    address: "Studio 123, Columbus, OH",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-120",
    clientId: "client-001",
    title: "Flutter App Development",
    description: "Create a Flutter mobile app for inventory management with barcode scanning.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 15000.00,
    category: "Mobile Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "proj-121",
    clientId: "client-001",
    title: "House Organizing",
    description: "Organize cluttered garage, closets, and basement. Sort, donate, and arrange items.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 400.00,
    category: "Cleaning",
    status: "POSTED",
    address: "567 Tidy Town, Kansas City, MO",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-122",
    clientId: "client-001",
    title: "Landing Page Design",
    description: "Design high-converting landing page with A/B testing setup and analytics integration.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-123",
    clientId: "client-001",
    title: "Deck Building",
    description: "Build 12x16 composite deck with stairs, railing, and built-in seating.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 8000.00,
    category: "Assembly",
    status: "POSTED",
    address: "789 Backyard Lane, Raleigh, NC",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-124",
    clientId: "client-001",
    title: "Excel Automation Scripts",
    description: "Create VBA macros to automate recurring Excel reports and data processing tasks.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 650.00,
    category: "Data Analysis",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-125",
    clientId: "client-001",
    title: "Window Cleaning Service",
    description: "Clean all windows inside and out for 2-story house with 20 windows.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 280.00,
    category: "Cleaning",
    status: "POSTED",
    address: "901 Clear View, Atlanta, GA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-126",
    clientId: "client-001",
    title: "Podcast Editing",
    description: "Edit and produce 10 podcast episodes with noise removal, mixing, and intro/outro.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1000.00,
    category: "Video Editing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-127",
    clientId: "client-001",
    title: "Cabinet Installation",
    description: "Install kitchen cabinets including upper and lower units with hardware.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2200.00,
    category: "Assembly",
    status: "POSTED",
    address: "234 Kitchen Way, Memphis, TN",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-128",
    clientId: "client-001",
    title: "Resume Writing Service",
    description: "Professional resume writing and optimization for tech industry positions.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 300.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-129",
    clientId: "client-001",
    title: "Event Videography",
    description: "Record and edit corporate event highlight video with drone footage.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2500.00,
    category: "Photography",
    status: "POSTED",
    address: "Convention Hall, Las Vegas, NV",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-130",
    clientId: "client-001",
    title: "Node.js API Development",
    description: "Build RESTful API with Node.js, Express, and MongoDB for social platform.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 6000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-131",
    clientId: "client-001",
    title: "Pressure Washing Business",
    description: "Pressure wash commercial building exterior including sidewalks and parking area.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1500.00,
    category: "Cleaning",
    status: "POSTED",
    address: "500 Commerce St, Dallas, TX",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-132",
    clientId: "client-001",
    title: "Illustration Package",
    description: "Create 15 custom illustrations for children's book with consistent style.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 2800.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-133",
    clientId: "client-001",
    title: "HVAC Maintenance",
    description: "Complete HVAC system inspection, filter replacement, and tune-up for office building.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 450.00,
    category: "Handyman",
    status: "POSTED",
    address: "300 Tech Park, San Jose, CA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-134",
    clientId: "client-001",
    title: "Blockchain Smart Contract",
    description: "Develop Solidity smart contract for NFT marketplace with minting and trading features.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 9000.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: "proj-135",
    clientId: "client-001",
    title: "Dog Training Sessions",
    description: "5 private dog training sessions for obedience and behavior modification.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 500.00,
    category: "Pet Care",
    status: "POSTED",
    address: "456 Puppy Place, San Antonio, TX",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-136",
    clientId: "client-001",
    title: "Motion Graphics Video",
    description: "Create animated explainer video with motion graphics for product launch.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 3500.00,
    category: "Video Editing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-137",
    clientId: "client-001",
    title: "Bathroom Renovation",
    description: "Full bathroom remodel including tile, vanity, toilet, and fixtures installation.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 12000.00,
    category: "Renovation",
    status: "POSTED",
    address: "789 Remodel Rd, Jacksonville, FL",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "proj-138",
    clientId: "client-001",
    title: "Financial Model Creation",
    description: "Build comprehensive financial model for startup funding presentation.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2000.00,
    category: "Accounting",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-139",
    clientId: "client-001",
    title: "Delivery Driver",
    description: "Deliver packages within 50 mile radius. Vehicle provided. 20 hours per week.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Delivery",
    status: "POSTED",
    address: "100 Distribution Center, Philadelphia, PA",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-140",
    clientId: "client-001",
    title: "SEO Audit Report",
    description: "Comprehensive SEO audit with keyword research, competitor analysis, and recommendations.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 750.00,
    category: "Marketing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-141",
    clientId: "client-001",
    title: "Personal Chef Service",
    description: "Prepare weekly meals for family of 4. Menu planning and grocery shopping included.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Personal Care",
    status: "POSTED",
    address: "567 Gourmet Ave, Boston, MA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-142",
    clientId: "client-001",
    title: "TypeScript Migration",
    description: "Migrate existing JavaScript codebase to TypeScript with proper typing and interfaces.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 4500.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-143",
    clientId: "client-001",
    title: "Appliance Repair",
    description: "Diagnose and repair washing machine, dryer, and dishwasher issues.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Handyman",
    status: "POSTED",
    address: "890 Appliance Way, Detroit, MI",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-144",
    clientId: "client-001",
    title: "Podcast Launch Package",
    description: "Complete podcast launch including intro music, artwork, hosting setup, and first episode edit.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Video Editing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-145",
    clientId: "client-001",
    title: "Sprinkler System Installation",
    description: "Install automatic sprinkler system for front and backyard with timer control.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2800.00,
    category: "Gardening",
    status: "POSTED",
    address: "234 Green Lawn, Milwaukee, WI",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-146",
    clientId: "client-001",
    title: "UI/UX Wireframing",
    description: "Create wireframes and prototypes for mobile banking application.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2200.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-147",
    clientId: "client-001",
    title: "Garage Door Repair",
    description: "Fix broken garage door springs, tracks, and opener mechanism.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 550.00,
    category: "Handyman",
    status: "POSTED",
    address: "456 Garage Lane, Baltimore, MD",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-148",
    clientId: "client-001",
    title: "Email Copywriting",
    description: "Write 20 promotional email sequences for product launch campaign.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 900.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-149",
    clientId: "client-001",
    title: "Corporate Headshots",
    description: "Professional headshot photography for 30 employees with studio and outdoor options.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1800.00,
    category: "Photography",
    status: "POSTED",
    address: "Corporate HQ, Seattle, WA",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-150",
    clientId: "client-001",
    title: "React Dashboard Components",
    description: "Build reusable React dashboard components with Material-UI integration.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 5500.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "proj-151",
    clientId: "client-001",
    title: "Shower Installation",
    description: "Install walk-in shower with glass doors, tile surround, and new fixtures.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 3500.00,
    category: "Renovation",
    status: "POSTED",
    address: "678 Bath Street, Louisville, KY",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-152",
    clientId: "client-001",
    title: "Payroll Setup Service",
    description: "Set up payroll system for small business with tax calculations and direct deposit.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1000.00,
    category: "Accounting",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-153",
    clientId: "client-001",
    title: "Moving Help Load/Unload",
    description: "Help loading and unloading moving truck for 2 bedroom apartment.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 400.00,
    category: "Moving",
    status: "POSTED",
    address: "901 Moving Day, Oklahoma City, OK",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-154",
    clientId: "client-001",
    title: "Google Ads Campaign",
    description: "Set up and manage Google Ads campaign with keyword research and A/B testing.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 3000.00,
    category: "Marketing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-155",
    clientId: "client-001",
    title: "Interior Design Consultation",
    description: "Provide interior design consultation and mood boards for living room and bedroom.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 700.00,
    category: "Design",
    status: "POSTED",
    address: "234 Design Dr, Albuquerque, NM",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-156",
    clientId: "client-001",
    title: "Tattoo Aftercare Products",
    description: "Research and source wholesale tattoo aftercare products for online store.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 500.00,
    category: "Research",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-157",
    clientId: "client-001",
    title: "Window Replacement",
    description: "Replace 10 windows with energy-efficient double pane windows.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 5000.00,
    category: "Renovation",
    status: "POSTED",
    address: "567 Window Way, Tucson, AZ",
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: "proj-158",
    clientId: "client-001",
    title: "REST API Documentation",
    description: "Document REST API endpoints with Swagger/OpenAPI specification.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-159",
    clientId: "client-001",
    title: "Warehouse Cleanup",
    description: "Clean and organize 5000 sq ft warehouse space including sorting and disposal.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Cleaning",
    status: "POSTED",
    address: "Industrial Park, Omaha, NE",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-160",
    clientId: "client-001",
    title: "Angular Enterprise App",
    description: "Build enterprise Angular application with role-based access control and audit logs.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 22000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "proj-161",
    clientId: "client-001",
    title: "Dog Boarding Setup",
    description: "Set up home-based dog boarding business with documentation and safety protocols.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Pet Care",
    status: "POSTED",
    address: "789 Pet Lane, Fresno, CA",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-162",
    clientId: "client-001",
    title: "3D Animation Project",
    description: "Create 3D animated product demo video with realistic rendering and effects.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 4000.00,
    category: "Video Editing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-163",
    clientId: "client-001",
    title: "Retaining Wall Construction",
    description: "Build 50 ft retaining wall with drainage system for hillside property.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 7500.00,
    category: "Assembly",
    status: "POSTED",
    address: "Hillside Estates, Sacramento, CA",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "proj-164",
    clientId: "client-001",
    title: "Sales Dashboard",
    description: "Build Power BI dashboard for sales performance tracking and forecasting.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2500.00,
    category: "Data Analysis",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-165",
    clientId: "client-001",
    title: "Gutter Cleaning Service",
    description: "Clean and inspect gutters on 2-story house, remove debris and check for leaks.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 180.00,
    category: "Cleaning",
    status: "POSTED",
    address: "321 Gutter Lane, Long Beach, CA",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-166",
    clientId: "client-001",
    title: "LinkedIn Profile Optimization",
    description: "Optimize LinkedIn profiles for 10 executives with professional summaries and keywords.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-167",
    clientId: "client-001",
    title: "Portrait Photography Session",
    description: "Family portrait photography session with 20 edited digital images.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 500.00,
    category: "Photography",
    status: "POSTED",
    address: "Central Park, New York, NY",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-168",
    clientId: "client-001",
    title: "GraphQL API Development",
    description: "Convert REST API to GraphQL with Apollo Server and schema design.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 7000.00,
    category: "Web Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-169",
    clientId: "client-001",
    title: "Floor Tiling Installation",
    description: "Install ceramic tile flooring in kitchen and bathroom areas.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2800.00,
    category: "Renovation",
    status: "POSTED",
    address: "674 Tile Lane, Oakland, CA",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-170",
    clientId: "client-001",
    title: "Bookkeeping Services",
    description: "Monthly bookkeeping and financial statement preparation for small business.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Accounting",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-171",
    clientId: "client-001",
    title: "Office Furniture Delivery",
    description: "Deliver and assemble office desks and chairs for 10 workstations.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 700.00,
    category: "Delivery",
    status: "POSTED",
    address: "Business Center, Miami, FL",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-172",
    clientId: "client-001",
    title: "Social Media Content Calendar",
    description: "Create 3-month social media content calendar with captions and hashtags.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 900.00,
    category: "Marketing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-173",
    clientId: "client-001",
    title: "Custom Closet Installation",
    description: "Design and install custom closet organization system for master bedroom.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1800.00,
    category: "Assembly",
    status: "POSTED",
    address: "891 Closet Way, Mesa, AZ",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-174",
    clientId: "client-001",
    title: "Content Moderation Setup",
    description: "Set up automated content moderation system with AI filtering and manual review queue.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 4000.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-175",
    clientId: "client-001",
    title: "Pest Control Treatment",
    description: "Comprehensive pest control treatment for home including inspection and follow-up.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Cleaning",
    status: "POSTED",
    address: "456 Bug Free Blvd, Cleveland, OH",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-176",
    clientId: "client-001",
    title: "Newsletter Design",
    description: "Design monthly newsletter template with responsive email formatting.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-177",
    clientId: "client-001",
    title: "Roof Inspection",
    description: "Professional roof inspection with detailed report and repair recommendations.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 400.00,
    category: "Handyman",
    status: "POSTED",
    address: "789 Rooftop Rd, Kansas City, KS",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-178",
    clientId: "client-001",
    title: "Localization Translation",
    description: "Localize website and app content for 5 languages including cultural adaptations.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 5000.00,
    category: "Translation",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-179",
    clientId: "client-001",
    title: "Outdoor Wedding Setup",
    description: "Set up outdoor wedding venue including chairs, arch, and decorations.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2000.00,
    category: "Assembly",
    status: "POSTED",
    address: "Garden Venue, Savannah, GA",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-180",
    clientId: "client-001",
    title: "Python Automation Scripts",
    description: "Create Python scripts to automate data entry and reporting tasks.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1500.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-181",
    clientId: "client-001",
    title: "Carpet Installation",
    description: "Install new carpet in 4 rooms including padding and transitions.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 2200.00,
    category: "Renovation",
    status: "POSTED",
    address: "567 Carpet Ct, Virginia Beach, VA",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-182",
    clientId: "client-001",
    title: "Financial Statement Preparation",
    description: "Prepare quarterly financial statements and variance analysis reports.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Accounting",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-183",
    clientId: "client-001",
    title: "Grocery Shopping Service",
    description: "Weekly grocery shopping and delivery for elderly client with specific dietary needs.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 200.00,
    category: "Personal Care",
    status: "POSTED",
    address: "123 Senior Lane, Tucson, AZ",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-184",
    clientId: "client-001",
    title: "Content Writing Package",
    description: "Write 15 blog posts on health and wellness topics, 1200 words each.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1100.00,
    category: "Writing",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-185",
    clientId: "client-001",
    title: "Studio Lighting Setup",
    description: "Set up professional photography studio lighting for product shoots.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Photography",
    status: "POSTED",
    address: "Photo Studio 45, Portland, OR",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-186",
    clientId: "client-001",
    title: "Kotlin Android App",
    description: "Develop native Android app for habit tracking with Material Design 3.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 11000.00,
    category: "Mobile Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: "proj-187",
    clientId: "client-001",
    title: "Fireplace Cleaning",
    description: "Clean and inspect chimney and fireplace for safe winter use.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 300.00,
    category: "Cleaning",
    status: "POSTED",
    address: "891 Hearth Ave, Buffalo, NY",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-188",
    clientId: "client-001",
    title: "Icon Set Design",
    description: "Design custom icon set of 100 icons for web and mobile applications.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1800.00,
    category: "Design",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-189",
    clientId: "client-001",
    title: "Security System Installation",
    description: "Install home security system with cameras, sensors, and monitoring setup.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1500.00,
    category: "Handyman",
    status: "POSTED",
    address: "234 Secure St, Anchorage, AK",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-190",
    clientId: "client-001",
    title: "AI Chatbot Development",
    description: "Build conversational AI chatbot with NLP for customer service automation.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 8000.00,
    category: "Software Development",
    status: "POSTED",
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },

  // 10 ONGOING (IN_PROGRESS) Projects - assigned to worker-021
  {
    id: "proj-011",
    clientId: "client-001",
    title: "Weekly Office Cleaning",
    description: "Regular weekly office cleaning for 3 floors including vacuuming, dusting, and bathroom sanitization.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 800.00,
    category: "Cleaning",
    status: "IN_PROGRESS",
    workerId: "worker-021",
    address: "123 Business Plaza, New York, NY",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-012",
    clientId: "client-001",
    title: "API Integration Project",
    description: "Integrate third-party payment APIs and CRM systems into existing web application.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 3500.00,
    category: "Web Development",
    status: "IN_PROGRESS",
    workerId: "worker-021",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-013",
    clientId: "client-001",
    title: "Pet Sitting Service",
    description: "Daily pet sitting for 2 dogs and 1 cat for one week while owner is on vacation.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 450.00,
    category: "Pet Care",
    status: "IN_PROGRESS",
    workerId: "worker-021",
    address: "654 Dogwood Drive, Boston, MA",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-014",
    clientId: "client-001",
    title: "Video Editing for YouTube",
    description: "Edit and produce weekly YouTube videos including thumbnails, intros, and captions.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 2000.00,
    category: "Video Editing",
    status: "SUBMITTED",
    workerId: "worker-021",
    submissionDescription: "Completed all 8 YouTube video edits with custom thumbnails, intro/outro animations, and auto-generated captions. Files are exported in 1080p and 4K. Please review the attached ZIP containing all final renders.",
    submissionFileName: "youtube_videos_final_v2.zip",
    submittedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 21).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-015",
    clientId: "client-001",
    title: "Carpet Cleaning",
    description: "Deep carpet cleaning for 4 rooms and stairs using professional equipment.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 300.00,
    category: "Cleaning",
    status: "IN_PROGRESS",
    workerId: "worker-021",
    address: "987 Elm Street, Denver, CO",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-016",
    clientId: "client-001",
    title: "Social Media Marketing",
    description: "Manage social media accounts with daily posts, stories, and engagement for 1 month.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1500.00,
    category: "Marketing",
    status: "IN_PROGRESS",
    workerId: "worker-021",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-017",
    clientId: "client-001",
    title: "Handyman Services",
    description: "Various minor repairs including door handle replacement, shelf mounting, and drywall patching.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 400.00,
    category: "Handyman",
    status: "SUBMITTED",
    workerId: "worker-021",
    address: "147 Maple Avenue, Portland, OR",
    submissionDescription: "All repairs completed: replaced 3 door handles, mounted 2 shelves (wall-anchored), and patched 2 drywall holes with sanding and primer. Photos of completed work are attached.",
    submissionFileName: "handyman_completion_photos.pdf",
    submittedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-018",
    clientId: "client-001",
    title: "Custom Software Development",
    description: "Develop inventory management system with barcode scanning and reporting features.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 12000.00,
    category: "Software Development",
    status: "IN_PROGRESS",
    workerId: "worker-008",
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-019",
    clientId: "client-001",
    title: "Personal Training Sessions",
    description: "10 personal training sessions for fitness goals including strength training and cardio.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 750.00,
    category: "Fitness",
    status: "IN_PROGRESS",
    workerId: "worker-009",
    address: "Gold's Gym Downtown, Houston, TX",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-020",
    clientId: "client-001",
    title: "Graphic Design for Marketing",
    description: "Create marketing materials including brochures, flyers, and social media graphics.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 1800.00,
    category: "Design",
    status: "IN_PROGRESS",
    workerId: "worker-010",
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },

  // 10 COMPLETED Projects - assigned to worker-021
  {
    id: "proj-021",
    clientId: "client-001",
    title: "Wedding Photography",
    description: "Full day wedding photography coverage with edited digital album and prints.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 3500.00,
    category: "Photography",
    status: "COMPLETED",
    workerId: "worker-021",
    address: "Sunset Gardens, Los Angeles, CA",
    completedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "proj-022",
    clientId: "client-001",
    title: "Website Development",
    description: "Built professional portfolio website with contact forms and blog integration.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 2800.00,
    category: "Web Development",
    status: "COMPLETED",
    workerId: "worker-021",
    completedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: "proj-023",
    clientId: "client-001",
    title: "Lawn Mowing Service",
    description: "Regular lawn mowing and edging for residential property every 2 weeks.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 200.00,
    category: "Gardening",
    status: "COMPLETED",
    workerId: "worker-021",
    address: "456 Oak Lane, Chicago, IL",
    completedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 100).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
  {
    id: "proj-024",
    clientId: "client-001",
    title: "Data Analysis Report",
    description: "Analyze sales data and create comprehensive report with visualizations and insights.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 600.00,
    category: "Data Analysis",
    status: "COMPLETED",
    workerId: "worker-014",
    completedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "proj-025",
    clientId: "client-001",
    title: "Home Renovation Planning",
    description: "Kitchen and bathroom renovation planning with design drawings and material suggestions.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 5500.00,
    category: "Renovation",
    status: "COMPLETED",
    workerId: "worker-015",
    completedAt: new Date(Date.now() - 86400000 * 75).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 150).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 75).toISOString(),
  },
  {
    id: "proj-026",
    clientId: "client-001",
    title: "Translation Services",
    description: "Translate 50 pages of legal documents from Spanish to English with certification.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1250.00,
    category: "Translation",
    status: "COMPLETED",
    workerId: "worker-016",
    completedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "proj-027",
    clientId: "client-001",
    title: "Dog Walking",
    description: "Daily dog walking service for 2 large dogs, 30 minutes each walk, for 2 weeks.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 350.00,
    category: "Pet Care",
    status: "COMPLETED",
    workerId: "worker-017",
    completedAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 55).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 25).toISOString(),
  },
  {
    id: "proj-028",
    clientId: "client-001",
    title: "Mobile App UI Design",
    description: "Design UI/UX for fitness tracking mobile application with screens and prototypes.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 4500.00,
    category: "Design",
    status: "COMPLETED",
    workerId: "worker-018",
    completedAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 110).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 50).toISOString(),
  },
  {
    id: "proj-029",
    clientId: "client-001",
    title: "Furniture Delivery",
    description: "Deliver and assemble new bedroom furniture set from store to apartment.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 275.00,
    category: "Delivery",
    status: "COMPLETED",
    workerId: "worker-019",
    completedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "proj-030",
    clientId: "client-001",
    title: "Accounting Services",
    description: "Monthly bookkeeping and tax preparation for small business.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 800.00,
    category: "Accounting",
    status: "COMPLETED",
    workerId: "worker-020",
    completedAt: new Date(Date.now() - 86400000 * 35).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 80).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },

  // IN_DISPUTE Projects - assigned to worker-021
  {
    id: "proj-031",
    clientId: "client-001",
    title: "E-Commerce Website Redesign",
    description: "Full redesign of online store including product pages, cart, and checkout flow. Dispute raised over scope of revisions not covered in original agreement.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 4500.00,
    category: "Web Development",
    status: "IN_DISPUTE",
    workerId: "worker-021",
    createdAt: new Date(Date.now() - 86400000 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-032",
    clientId: "client-001",
    title: "Mobile App UI Design",
    description: "Design UI/UX for iOS and Android fitness tracking app with 20+ screens. Dispute raised over delayed delivery and incomplete screen designs.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2800.00,
    category: "Design",
    status: "IN_DISPUTE",
    workerId: "worker-021",
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-033",
    clientId: "client-001",
    title: "Office Deep Cleaning Service",
    description: "Deep cleaning of 3-floor office building including carpets, windows, and common areas. Dispute raised over quality of work and missed areas.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 1200.00,
    category: "Cleaning",
    status: "IN_DISPUTE",
    workerId: "worker-021",
    address: "350 Corporate Blvd, Chicago, IL",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },

  // SUBMITTED (In Review) Projects - additional for client-001
  {
    id: "proj-034",
    clientId: "client-001",
    title: "Brand Identity Package",
    description: "Full brand identity including logo, color palette, typography, and brand guidelines document.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1800.00,
    category: "Design",
    status: "SUBMITTED",
    workerId: "worker-010",
    submissionDescription: "Delivered the complete brand identity package: primary logo + 3 variations, full color palette with HEX/RGB/CMYK codes, typography system, and a 24-page brand guidelines PDF. All source files (AI, SVG, PNG) are included in the attachment.",
    submissionFileName: "brand_identity_package_final.zip",
    submittedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-035",
    clientId: "client-001",
    title: "React Dashboard Development",
    description: "Build an analytics dashboard with charts, tables, and real-time data updates using React.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 5500.00,
    category: "Web Development",
    status: "SUBMITTED",
    workerId: "worker-012",
    submissionDescription: "React dashboard is fully built and deployed to staging. Includes 6 chart types (line, bar, doughnut, heatmap), sortable/filterable data tables, real-time WebSocket updates, and dark mode toggle. Test credentials and deployment link are in the README inside the zip.",
    submissionFileName: "react_dashboard_v1.0.zip",
    submittedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 35).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-036",
    clientId: "client-001",
    title: "Electrical Wiring Upgrade",
    description: "Upgrade electrical panel and rewire 4 rooms to meet current building code standards.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 3200.00,
    category: "Electrical",
    status: "SUBMITTED",
    workerId: "worker-007",
    address: "88 Hillside Road, Phoenix, AZ",
    submissionDescription: "Panel upgraded from 100A to 200A service. All 4 rooms rewired with 12-gauge copper, GFCI outlets installed in wet areas, and arc-fault breakers added per code. Passed city inspection on first attempt — permit and inspection certificate included in attachment.",
    submissionFileName: "electrical_upgrade_permit_inspection.pdf",
    submittedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "proj-037",
    clientId: "client-001",
    title: "Copywriting for Product Launch",
    description: "Write website copy, email sequences, and ad creatives for upcoming SaaS product launch.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 2200.00,
    category: "Copywriting",
    status: "SUBMITTED",
    workerId: "worker-015",
    submissionDescription: "Delivered all copy assets: 5-page website copy (hero, features, pricing, about, FAQ), 7-email onboarding sequence, 12 ad creatives (Google + Meta), and 3 landing page variants for A/B testing. All in a structured Google Doc with revision notes.",
    submissionFileName: "product_launch_copy_package.docx",
    submittedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-038",
    clientId: "client-001",
    title: "Plumbing Repair Service",
    description: "Fix leaking pipes under kitchen sink and replace bathroom faucets in two bathrooms.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 650.00,
    category: "Plumbing",
    status: "SUBMITTED",
    workerId: "worker-009",
    address: "215 Cedar Lane, Miami, FL",
    submissionDescription: "Replaced P-trap and supply lines under kitchen sink — no more leaks. Both bathroom faucets swapped out for the Moen Arbor models as requested. Ran water for 30 minutes to confirm no drips. Before/after photos included in the attachment.",
    submissionFileName: "plumbing_repair_before_after.pdf",
    submittedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },

  // Additional IN_DISPUTE Projects for client-001
  {
    id: "proj-039",
    clientId: "client-001",
    title: "App Development - Fitness Tracker",
    description: "Cross-platform fitness tracking app with workout logging and nutrition tracking. Dispute raised over missing features promised in the original scope.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 8000.00,
    category: "Mobile Development",
    status: "IN_DISPUTE",
    workerId: "worker-011",
    createdAt: new Date(Date.now() - 86400000 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-040",
    clientId: "client-001",
    title: "Interior Painting - Master Bedroom",
    description: "Paint master bedroom and en-suite bathroom with premium paint. Dispute raised over uneven coat and paint splatter on trim.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 900.00,
    category: "Painting",
    status: "IN_DISPUTE",
    workerId: "worker-014",
    address: "44 Birchwood Drive, Seattle, WA",
    createdAt: new Date(Date.now() - 86400000 * 22).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-041",
    clientId: "client-001",
    title: "SEO Audit and Optimization",
    description: "Full technical SEO audit and on-page optimization for 50-page website. Dispute raised over lack of ranking improvements after 2 months.",
    type: "VIRTUAL",
    budgetModel: "FIXED",
    budget: 1400.00,
    category: "Marketing",
    status: "IN_DISPUTE",
    workerId: "worker-016",
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "proj-042",
    clientId: "client-001",
    title: "Catering for Corporate Event",
    description: "Full catering service for 100-person corporate dinner including setup and cleanup. Dispute raised over late arrival and incorrect menu items.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 4500.00,
    category: "Catering",
    status: "IN_DISPUTE",
    workerId: "worker-018",
    address: "500 Convention Center Drive, Boston, MA",
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-043",
    clientId: "client-001",
    title: "Database Migration to Cloud",
    description: "Migrate on-premise SQL Server databases to AWS RDS with zero downtime strategy. Dispute raised over data inconsistencies found post-migration.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 6500.00,
    category: "Cloud & DevOps",
    status: "IN_DISPUTE",
    workerId: "worker-020",
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },

  // Contractor-only projects (contractorOnly: true) — large, enterprise-scale
  // POSTED (available for contractor bidding)
  {
    id: "proj-C01",
    clientId: "client-002",
    title: "Enterprise ERP System Implementation",
    description: "Full implementation of an enterprise resource planning system across 5 departments. Includes data migration, staff training, and 6-month support SLA. Team of 8–12 specialists required.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 120000.00,
    category: "Software Development",
    status: "POSTED",
    contractorOnly: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "proj-C02",
    clientId: "client-002",
    title: "Commercial Building Renovation",
    description: "Full renovation of a 12,000 sq ft commercial office building including structural, electrical, plumbing, HVAC, and interior fit-out. Requires licensed contractor with bonding.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 850000.00,
    category: "Construction",
    status: "POSTED",
    contractorOnly: true,
    address: "1200 Commerce Park, Houston, TX",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "proj-C03",
    clientId: "client-003",
    title: "City-Wide Network Infrastructure Upgrade",
    description: "Upgrade fiber optic and wireless network infrastructure across 40 municipal buildings. Includes cabling, hardware installation, and configuration. Multi-crew operation required.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 480000.00,
    category: "IT Infrastructure",
    status: "POSTED",
    contractorOnly: true,
    address: "City Hall, Denver, CO",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "proj-C04",
    clientId: "client-002",
    title: "Hospital Facility Management System",
    description: "Design, develop, and deploy a comprehensive facility management system for a 500-bed hospital. Includes asset tracking, maintenance scheduling, compliance reporting, and staff portals.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 95000.00,
    category: "Healthcare IT",
    status: "POSTED",
    contractorOnly: true,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "proj-C05",
    clientId: "client-003",
    title: "Corporate Campus Landscaping & Hardscape",
    description: "Complete landscaping, hardscape, irrigation, and exterior lighting for a 25-acre corporate campus. Multi-phase project requiring crews for earthwork, planting, and hardscape.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 320000.00,
    category: "Landscaping",
    status: "POSTED",
    contractorOnly: true,
    address: "500 Innovation Blvd, San Jose, CA",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "proj-C06",
    clientId: "client-004",
    title: "Multi-Platform SaaS Product Development",
    description: "Build a B2B SaaS platform from scratch: web app, iOS/Android apps, REST API, admin portal, and analytics dashboard. Full-stack team needed for a 12-month build.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 250000.00,
    category: "Software Development",
    status: "POSTED",
    contractorOnly: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-C07",
    clientId: "client-004",
    title: "Industrial Warehouse Construction",
    description: "Construction of a 50,000 sq ft industrial warehouse with loading docks, fire suppression, climate control, and solar roofing. Requires general contractor with industrial experience.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 2200000.00,
    category: "Construction",
    status: "POSTED",
    contractorOnly: true,
    address: "7800 Industrial Pkwy, Columbus, OH",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "proj-C08",
    clientId: "client-003",
    title: "Cybersecurity Infrastructure Overhaul",
    description: "End-to-end security audit and infrastructure hardening for a financial services firm. Includes penetration testing, SIEM deployment, SOC setup, and staff security training program.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 175000.00,
    category: "Cybersecurity",
    status: "POSTED",
    contractorOnly: true,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },

  // ASSIGNED — contractor-001 has accepted these
  {
    id: "proj-C09",
    clientId: "client-002",
    contractorId: "contractor-001",
    title: "Smart Office IoT Integration",
    description: "Deploy IoT sensors, smart lighting, HVAC automation, and a central monitoring dashboard across a 6-floor office. Coordinate hardware, firmware, and software teams.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 140000.00,
    category: "IT Infrastructure",
    status: "ASSIGNED",
    contractorOnly: true,
    address: "900 Tech Tower, Seattle, WA",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: "proj-C10",
    clientId: "client-003",
    contractorId: "contractor-001",
    title: "Healthcare Data Platform Migration",
    description: "Migrate 10 years of patient records and clinical data from legacy on-premise systems to a HIPAA-compliant cloud platform. Includes ETL pipelines, QA, and rollback plans.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 88000.00,
    category: "Healthcare IT",
    status: "ASSIGNED",
    contractorOnly: true,
    createdAt: new Date(Date.now() - 86400000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },

  // IN_PROGRESS — contractor-001 actively working
  {
    id: "proj-C11",
    clientId: "client-004",
    contractorId: "contractor-001",
    title: "Retail Chain POS & Inventory System",
    description: "Develop and roll out a unified POS and inventory management system across 35 retail locations. Includes hardware procurement, software, training, and 3-month hypercare.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 210000.00,
    category: "Software Development",
    status: "IN_PROGRESS",
    contractorOnly: true,
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "proj-C12",
    clientId: "client-002",
    contractorId: "contractor-001",
    title: "Mixed-Use Development Site Preparation",
    description: "Site clearing, grading, utility rough-in, and foundation work for a 4-building mixed-use residential and retail development on a 3-acre lot.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 550000.00,
    category: "Construction",
    status: "IN_PROGRESS",
    contractorOnly: true,
    address: "2100 Urban District, Portland, OR",
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },

  // COMPLETED — historical
  {
    id: "proj-C13",
    clientId: "client-003",
    contractorId: "contractor-001",
    title: "Airport Terminal Digital Signage Network",
    description: "Design, supply, and install a 200-screen digital signage network for a regional airport terminal. Includes content management system and 2-year maintenance agreement.",
    type: "PHYSICAL",
    budgetModel: "FIXED",
    budget: 380000.00,
    category: "IT Infrastructure",
    status: "COMPLETED",
    contractorOnly: true,
    address: "Regional Airport, Nashville, TN",
    completedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: "proj-C14",
    clientId: "client-004",
    contractorId: "contractor-001",
    title: "Government e-Permitting Platform",
    description: "Built a citizen-facing e-permitting portal and back-office processing system for a municipal government. Integrated with GIS, payment gateway, and existing legacy databases.",
    type: "VIRTUAL",
    budgetModel: "MILESTONE",
    budget: 165000.00,
    category: "Government IT",
    status: "COMPLETED",
    contractorOnly: true,
    completedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },

  // IN_DISPUTE
  {
    id: "proj-C15",
    clientId: "client-002",
    contractorId: "contractor-001",
    title: "Corporate HQ Interior Fit-Out",
    description: "Full interior fit-out of 8,000 sq ft corporate HQ including partitioning, flooring, ceilings, AV systems, and furniture installation. Dispute over delay penalties and change-order costs.",
    type: "PHYSICAL",
    budgetModel: "MILESTONE",
    budget: 720000.00,
    category: "Construction",
    status: "IN_DISPUTE",
    contractorOnly: true,
    address: "400 Executive Plaza, Dallas, TX",
    createdAt: new Date(Date.now() - 86400000 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

export function getProjectsByStatus(status: string): Project[] {
  return projects.filter(p => p.status === status);
}

export function getProjectById(id: string): Project | undefined {
  return projects.find(p => p.id === id);
}

export function getProjectsByClientId(clientId: string): Project[] {
  return projects.filter(p => p.clientId === clientId);
}

export function addProject(project: Omit<Project, "id" | "createdAt" | "updatedAt">): Project {
  const newProject: Project = {
    ...project,
    id: `proj-${Date.now()}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  projects.push(newProject);
  return newProject;
}

export function updateProject(id: string, updates: Partial<Project>): Project | undefined {
  const index = projects.findIndex(p => p.id === id);
  if (index === -1) return undefined;
  
  projects[index] = {
    ...projects[index],
    ...updates,
    updatedAt: new Date().toISOString(),
  };
  return projects[index];
}
