export interface Milestone {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  amount: number;
  order: number;
  status: "PENDING" | "IN_PROGRESS" | "SUBMITTED" | "APPROVED" | "IN_DISPUTE";
  dueDate?: string;
  submittedAt?: string;
  approvedAt?: string;
}

export const milestones: Milestone[] = [
  // Milestones for Website Redesign (proj-001)
  {
    id: "ms-001",
    projectId: "proj-001",
    title: "Design Phase",
    description: "Create wireframes, mockups, and design system for all pages",
    amount: 1500.00,
    order: 1,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString(),
  },
  {
    id: "ms-002",
    projectId: "proj-001",
    title: "Frontend Development",
    description: "Implement responsive UI components and pages",
    amount: 2000.00,
    order: 2,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 21).toISOString(),
  },
  {
    id: "ms-003",
    projectId: "proj-001",
    title: "Backend Integration",
    description: "Connect frontend with backend APIs and test all functionality",
    amount: 1000.00,
    order: 3,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 28).toISOString(),
  },
  {
    id: "ms-004",
    projectId: "proj-001",
    title: "Testing & Deployment",
    description: "QA testing, bug fixes, and production deployment",
    amount: 500.00,
    order: 4,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 35).toISOString(),
  },

  // Milestones for Mobile App (proj-003)
  {
    id: "ms-005",
    projectId: "proj-003",
    title: "UI/UX Design",
    description: "Design all screens, user flows, and navigation structure",
    amount: 3000.00,
    order: 1,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 14).toISOString(),
  },
  {
    id: "ms-006",
    projectId: "proj-003",
    title: "iOS Development",
    description: "Build native iOS app with all core features",
    amount: 4500.00,
    order: 2,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 35).toISOString(),
  },
  {
    id: "ms-007",
    projectId: "proj-003",
    title: "Android Development",
    description: "Build native Android app with all core features",
    amount: 4500.00,
    order: 3,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 50).toISOString(),
  },
  {
    id: "ms-008",
    projectId: "proj-003",
    title: "Backend API & Testing",
    description: "Build backend services, integrate APIs, and perform QA testing",
    amount: 3000.00,
    order: 4,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 60).toISOString(),
  },

  // Milestones for Garden Landscaping (proj-006)
  {
    id: "ms-009",
    projectId: "proj-006",
    title: "Site Preparation",
    description: "Clear existing vegetation and prepare soil",
    amount: 1000.00,
    order: 1,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
  },
  {
    id: "ms-010",
    projectId: "proj-006",
    title: "Plant Installation",
    description: "Plant trees, shrubs, and flowers according to design",
    amount: 2000.00,
    order: 2,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
  },
  {
    id: "ms-011",
    projectId: "proj-006",
    title: "Hardscape & Irrigation",
    description: "Install pathways, irrigation system, and outdoor lighting",
    amount: 1500.00,
    order: 3,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 8).toISOString(),
  },

  // Milestones for E-commerce Platform (proj-009)
  {
    id: "ms-012",
    projectId: "proj-009",
    title: "Requirements & Design",
    description: "Gather requirements, create wireframes, and design system",
    amount: 4000.00,
    order: 1,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 15).toISOString(),
  },
  {
    id: "ms-013",
    projectId: "proj-009",
    title: "Frontend Development",
    description: "Build responsive storefront with product catalog and cart",
    amount: 8000.00,
    order: 2,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 45).toISOString(),
  },
  {
    id: "ms-014",
    projectId: "proj-009",
    title: "Backend & Payments",
    description: "Build admin panel, integrate payment gateways, and inventory system",
    amount: 9000.00,
    order: 3,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 70).toISOString(),
  },
  {
    id: "ms-015",
    projectId: "proj-009",
    title: "Testing & Launch",
    description: "QA testing, bug fixes, and production deployment",
    amount: 4000.00,
    order: 4,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 90).toISOString(),
  },

  // Milestones for API Integration (proj-012) - IN PROGRESS
  {
    id: "ms-016",
    projectId: "proj-012",
    title: "Stripe Integration",
    description: "Integrate Stripe payment processing with existing system",
    amount: 1200.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 10).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "ms-017",
    projectId: "proj-012",
    title: "PayPal Integration",
    description: "Add PayPal as additional payment option",
    amount: 1000.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "ms-018",
    projectId: "proj-012",
    title: "CRM Integration",
    description: "Integrate Salesforce CRM for customer management",
    amount: 1300.00,
    order: 3,
    status: "IN_PROGRESS",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
  },

  // Milestones for Custom Software (proj-018) - IN PROGRESS
  {
    id: "ms-019",
    projectId: "proj-018",
    title: "Analysis & Planning",
    description: "Business analysis and technical specification",
    amount: 2000.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 30).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 28).toISOString(),
  },
  {
    id: "ms-020",
    projectId: "proj-018",
    title: "Database Design",
    description: "Design database schema and create migration scripts",
    amount: 2000.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 15).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: "ms-021",
    projectId: "proj-018",
    title: "Core Features Development",
    description: "Build inventory management and barcode scanning features",
    amount: 4000.00,
    order: 3,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "ms-022",
    projectId: "proj-018",
    title: "Reporting Module",
    description: "Build analytics dashboard and reporting features",
    amount: 2500.00,
    order: 4,
    status: "IN_PROGRESS",
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
  },
  {
    id: "ms-023",
    projectId: "proj-018",
    title: "Deployment & Training",
    description: "Deploy to production and train staff",
    amount: 1500.00,
    order: 5,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 20).toISOString(),
  },

  // Milestones for Video Editing (proj-014) - IN PROGRESS
  {
    id: "ms-024",
    projectId: "proj-014",
    title: "Week 1-2 Videos",
    description: "Edit and deliver first 4 videos with thumbnails and captions",
    amount: 400.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 7).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "ms-025",
    projectId: "proj-014",
    title: "Week 3-4 Videos",
    description: "Edit and deliver next 4 videos with thumbnails and captions",
    amount: 400.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "ms-026",
    projectId: "proj-014",
    title: "Week 5-6 Videos",
    description: "Edit and deliver final 4 videos with thumbnails and captions",
    amount: 400.00,
    order: 3,
    status: "IN_PROGRESS",
    dueDate: new Date(Date.now() + 86400000 * 7).toISOString(),
  },
  {
    id: "ms-027",
    projectId: "proj-014",
    title: "Channel Branding",
    description: "Create intro/outro animations and channel branding kit",
    amount: 800.00,
    order: 4,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 14).toISOString(),
  },

  // Milestones for Graphic Design (proj-020) - IN PROGRESS
  {
    id: "ms-028",
    projectId: "proj-020",
    title: "Brand Identity Package",
    description: "Create logo variations, color palette, and brand guidelines",
    amount: 600.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 10).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: "ms-029",
    projectId: "proj-020",
    title: "Brochures & Flyers",
    description: "Design print materials for marketing campaigns",
    amount: 500.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "ms-030",
    projectId: "proj-020",
    title: "Social Media Graphics",
    description: "Create templates for Instagram, Facebook, and Twitter posts",
    amount: 400.00,
    order: 3,
    status: "IN_PROGRESS",
    dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
  },
  {
    id: "ms-031",
    projectId: "proj-020",
    title: "Presentation Templates",
    description: "Design PowerPoint and keynote presentation templates",
    amount: 300.00,
    order: 4,
    status: "PENDING",
    dueDate: new Date(Date.now() + 86400000 * 10).toISOString(),
  },

  // Milestones for COMPLETED projects
  {
    id: "ms-032",
    projectId: "proj-022",
    title: "Website Design",
    description: "Create portfolio website design with mockups",
    amount: 800.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 100).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 95).toISOString(),
  },
  {
    id: "ms-033",
    projectId: "proj-022",
    title: "Website Development",
    description: "Build and deploy the portfolio website",
    amount: 2000.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 65).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 62).toISOString(),
  },

  {
    id: "ms-034",
    projectId: "proj-025",
    title: "Kitchen Design",
    description: "Kitchen renovation design with 3D renderings",
    amount: 1500.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 130).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 125).toISOString(),
  },
  {
    id: "ms-035",
    projectId: "proj-025",
    title: "Bathroom Design",
    description: "Bathroom renovation design with material selection",
    amount: 1500.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 110).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 105).toISOString(),
  },
  {
    id: "ms-036",
    projectId: "proj-025",
    title: "Project Management",
    description: "Contractor coordination and project oversight",
    amount: 2500.00,
    order: 3,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 78).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 75).toISOString(),
  },

  {
    id: "ms-037",
    projectId: "proj-028",
    title: "App Wireframes",
    description: "Create wireframes for all app screens and user flows",
    amount: 1000.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 95).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 90).toISOString(),
  },
  {
    id: "ms-038",
    projectId: "proj-028",
    title: "UI Design",
    description: "Design all screens with Figma including dark mode",
    amount: 2000.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 70).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 65).toISOString(),
  },
  {
    id: "ms-039",
    projectId: "proj-028",
    title: "Prototype",
    description: "Create interactive prototype with animations",
    amount: 1500.00,
    order: 3,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 52).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 50).toISOString(),
  },

  {
    id: "ms-040",
    projectId: "proj-030",
    title: "Bookkeeping Setup",
    description: "Set up chart of accounts and connect bank feeds",
    amount: 200.00,
    order: 1,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 70).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 68).toISOString(),
  },
  {
    id: "ms-041",
    projectId: "proj-030",
    title: "Monthly Reports",
    description: "Prepare monthly financial statements and reports",
    amount: 300.00,
    order: 2,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 40).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 38).toISOString(),
  },
  {
    id: "ms-042",
    projectId: "proj-030",
    title: "Tax Preparation",
    description: "Annual tax preparation and filing",
    amount: 300.00,
    order: 3,
    status: "APPROVED",
    dueDate: new Date(Date.now() - 86400000 * 35).toISOString(),
    approvedAt: new Date(Date.now() - 86400000 * 35).toISOString(),
  },
];

export function getMilestonesByProjectId(projectId: string): Milestone[] {
  return milestones.filter(m => m.projectId === projectId);
}

export function getMilestoneById(id: string): Milestone | undefined {
  return milestones.find(m => m.id === id);
}

export function updateMilestoneStatus(id: string, status: Milestone["status"]): Milestone | undefined {
  const index = milestones.findIndex(m => m.id === id);
  if (index === -1) return undefined;
  
  milestones[index].status = status;
  if (status === "APPROVED") {
    milestones[index].approvedAt = new Date().toISOString();
  }
  return milestones[index];
}
