export interface Offer {
  id: string;
  projectId: string;
  workerId: string;
  workerName: string;
  workerAvatar: string;
  workerRating: number;
  workerCompletedTasks: number;
  amount: number;
  terms: string;
  estimatedDays: number;
  status: "PENDING" | "ACCEPTED" | "REJECTED" | "WITHDRAWN";
  createdAt: string;
}

export const offers: Offer[] = [
  {
    id: "offer-001",
    projectId: "proj-001",
    workerId: "worker-021",
    workerName: "Alex Thompson",
    workerAvatar: "/images/team/freelancer-1.png",
    workerRating: 4.9,
    workerCompletedTasks: 87,
    amount: 4800.00,
    terms: "I can complete this website redesign in 5 weeks with modern React/Next.js stack. I'll include responsive design, SEO optimization, and accessibility features.",
    estimatedDays: 35,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "offer-002",
    projectId: "proj-001",
    workerId: "worker-027",
    workerName: "Michael Chen",
    workerAvatar: "/images/team/freelancer-2.png",
    workerRating: 4.8,
    workerCompletedTasks: 65,
    amount: 5200.00,
    terms: "Premium quality website redesign with Vue.js. Includes Figma designs, responsive development, and 3 months of support.",
    estimatedDays: 28,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "offer-003",
    projectId: "proj-002",
    workerId: "worker-022",
    workerName: "Maria Garcia",
    workerAvatar: "/images/team/freelancer-3.png",
    workerRating: 4.7,
    workerCompletedTasks: 54,
    amount: 320.00,
    terms: "Professional deep cleaning service using eco-friendly products. I have all the necessary equipment and supplies.",
    estimatedDays: 1,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "offer-004",
    projectId: "proj-003",
    workerId: "worker-025",
    workerName: "David Lee",
    workerAvatar: "/images/team/freelancer-4.png",
    workerRating: 4.9,
    workerCompletedTasks: 93,
    amount: 14500.00,
    terms: "Full native iOS and Android app development with React Native. Includes real-time tracking, payment integration, and admin dashboard.",
    estimatedDays: 60,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "offer-005",
    projectId: "proj-003",
    workerId: "worker-021",
    workerName: "Alex Thompson",
    workerAvatar: "/images/team/freelancer-1.png",
    workerRating: 4.9,
    workerCompletedTasks: 87,
    amount: 13800.00,
    terms: "Cross-platform Flutter app development with beautiful UI, real-time tracking, and Stripe payment integration.",
    estimatedDays: 45,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "offer-006",
    projectId: "proj-004",
    workerId: "worker-023",
    workerName: "James Wilson",
    workerAvatar: "/images/team/freelancer-5.png",
    workerRating: 4.8,
    workerCompletedTasks: 72,
    amount: 750.00,
    terms: "Professional moving service with packing materials, truck, and 2 helpers. Fully insured.",
    estimatedDays: 1,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "offer-007",
    projectId: "proj-005",
    workerId: "worker-028",
    workerName: "Lisa Anderson",
    workerAvatar: "/images/team/freelancer-3.png",
    workerRating: 4.7,
    workerCompletedTasks: 51,
    amount: 450.00,
    terms: "Modern minimalist logo design with 3 concepts, unlimited revisions, and all source files included.",
    estimatedDays: 5,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "offer-008",
    projectId: "proj-006",
    workerId: "worker-024",
    workerName: "Sarah Johnson",
    workerAvatar: "/images/team/freelancer-4.png",
    workerRating: 4.6,
    workerCompletedTasks: 45,
    amount: 4200.00,
    terms: "Complete garden makeover with native plants, drip irrigation system, and decorative pathways.",
    estimatedDays: 10,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "offer-009",
    projectId: "proj-007",
    workerId: "worker-026",
    workerName: "Emma Brown",
    workerAvatar: "/images/team/freelancer-1.png",
    workerRating: 4.5,
    workerCompletedTasks: 38,
    amount: 1800.00,
    terms: "SEO-optimized content with keyword research, meta descriptions, and engaging writing style.",
    estimatedDays: 14,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "offer-010",
    projectId: "proj-008",
    workerId: "worker-025",
    workerName: "David Lee",
    workerAvatar: "/images/team/freelancer-5.png",
    workerRating: 4.9,
    workerCompletedTasks: 93,
    amount: 1100.00,
    terms: "Professional event photography with high-end equipment, same-day preview, and 200+ edited photos.",
    estimatedDays: 1,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "offer-011",
    projectId: "proj-009",
    workerId: "worker-021",
    workerName: "Alex Thompson",
    workerAvatar: "/images/team/freelancer-1.png",
    workerRating: 4.9,
    workerCompletedTasks: 87,
    amount: 24000.00,
    terms: "Full-stack e-commerce platform with Shopify integration, inventory management, and payment processing.",
    estimatedDays: 90,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: "offer-012",
    projectId: "proj-009",
    workerId: "worker-027",
    workerName: "Michael Chen",
    workerAvatar: "/images/team/freelancer-2.png",
    workerRating: 4.8,
    workerCompletedTasks: 65,
    amount: 22000.00,
    terms: "Custom e-commerce solution with WooCommerce, Stripe, and advanced analytics dashboard.",
    estimatedDays: 75,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "offer-013",
    projectId: "proj-010",
    workerId: "worker-023",
    workerName: "James Wilson",
    workerAvatar: "/images/team/freelancer-3.png",
    workerRating: 4.8,
    workerCompletedTasks: 72,
    amount: 200.00,
    terms: "Quick and professional furniture assembly with all tools included. Can complete in 2-3 hours.",
    estimatedDays: 1,
    status: "PENDING",
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "offer-014",
    projectId: "proj-011",
    workerId: "worker-001",
    workerName: "Maria Garcia",
    workerAvatar: "/images/team/freelancer-4.png",
    workerRating: 4.7,
    workerCompletedTasks: 54,
    amount: 750.00,
    terms: "Weekly office cleaning service with all supplies included. Flexible scheduling.",
    estimatedDays: 1,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: "offer-015",
    projectId: "proj-012",
    workerId: "worker-002",
    workerName: "Alex Thompson",
    workerAvatar: "/images/team/freelancer-5.png",
    workerRating: 4.9,
    workerCompletedTasks: 87,
    amount: 3200.00,
    terms: "Professional API integration with Stripe, PayPal, and Salesforce CRM.",
    estimatedDays: 15,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 28).toISOString(),
  },
  {
    id: "offer-016",
    projectId: "proj-013",
    workerId: "worker-003",
    workerName: "Emma Brown",
    workerAvatar: "/images/team/freelancer-1.png",
    workerRating: 4.5,
    workerCompletedTasks: 38,
    amount: 420.00,
    terms: "Daily pet sitting with feeding, walks, and lots of affection for your pets!",
    estimatedDays: 7,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: "offer-017",
    projectId: "proj-014",
    workerId: "worker-004",
    workerName: "Michael Chen",
    workerAvatar: "/images/team/freelancer-2.png",
    workerRating: 4.8,
    workerCompletedTasks: 65,
    amount: 1800.00,
    terms: "Weekly video editing with intro animations, thumbnails, and captions in Final Cut Pro.",
    estimatedDays: 7,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: "offer-018",
    projectId: "proj-015",
    workerId: "worker-005",
    workerName: "Sarah Johnson",
    workerAvatar: "/images/team/freelancer-3.png",
    workerRating: 4.6,
    workerCompletedTasks: 45,
    amount: 280.00,
    terms: "Professional carpet cleaning with industrial equipment. Stain removal included.",
    estimatedDays: 1,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "offer-019",
    projectId: "proj-016",
    workerId: "worker-006",
    workerName: "David Lee",
    workerAvatar: "/images/team/freelancer-4.png",
    workerRating: 4.9,
    workerCompletedTasks: 93,
    amount: 1400.00,
    terms: "Social media management with daily posts, stories, engagement, and monthly analytics report.",
    estimatedDays: 30,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: "offer-020",
    projectId: "proj-017",
    workerId: "worker-007",
    workerName: "Lisa Anderson",
    workerAvatar: "/images/team/freelancer-5.png",
    workerRating: 4.7,
    workerCompletedTasks: 51,
    amount: 380.00,
    terms: "Handyman services with quality workmanship. Various repairs and installations.",
    estimatedDays: 2,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "offer-021",
    projectId: "proj-018",
    workerId: "worker-008",
    workerName: "James Wilson",
    workerAvatar: "/images/team/freelancer-1.png",
    workerRating: 4.8,
    workerCompletedTasks: 72,
    amount: 11000.00,
    terms: "Custom inventory management system with barcode scanning, reporting, and cloud backup.",
    estimatedDays: 45,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 40).toISOString(),
  },
  {
    id: "offer-022",
    projectId: "proj-019",
    workerId: "worker-009",
    workerName: "Emma Brown",
    workerAvatar: "/images/team/freelancer-2.png",
    workerRating: 4.5,
    workerCompletedTasks: 38,
    amount: 700.00,
    terms: "Personal training with customized workout plans and nutrition guidance.",
    estimatedDays: 30,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: "offer-023",
    projectId: "proj-020",
    workerId: "worker-010",
    workerName: "Alex Thompson",
    workerAvatar: "/images/team/freelancer-3.png",
    workerRating: 4.9,
    workerCompletedTasks: 87,
    amount: 1650.00,
    terms: "Professional marketing design with consistent branding across all materials.",
    estimatedDays: 14,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: "offer-024",
    projectId: "proj-021",
    workerId: "worker-011",
    workerName: "Michael Chen",
    workerAvatar: "/images/team/freelancer-4.png",
    workerRating: 4.8,
    workerCompletedTasks: 65,
    amount: 3200.00,
    terms: "Full wedding day coverage with 500+ edited photos and professionally designed album.",
    estimatedDays: 1,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 85).toISOString(),
  },
  {
    id: "offer-025",
    projectId: "proj-022",
    workerId: "worker-012",
    workerName: "Sarah Johnson",
    workerAvatar: "/images/team/freelancer-5.png",
    workerRating: 4.6,
    workerCompletedTasks: 45,
    amount: 2600.00,
    terms: "Professional portfolio website with custom design, animations, and contact forms.",
    estimatedDays: 21,
    status: "ACCEPTED",
    createdAt: new Date(Date.now() - 86400000 * 110).toISOString(),
  },
];

export function getOffersByProjectId(projectId: string): Offer[] {
  return offers.filter(o => o.projectId === projectId);
}

export function getAllOffers(): Offer[] {
  return offers;
}

export function getOfferById(id: string): Offer | undefined {
  return offers.find(o => o.id === id);
}

export function updateOfferStatus(id: string, status: Offer["status"]): Offer | undefined {
  const index = offers.findIndex(o => o.id === id);
  if (index === -1) return undefined;
  
  offers[index].status = status;
  return offers[index];
}
